import { listColumnMetaWithSlNo } from "./exportColumnResolver.js";

const fmtDate = (d) => {
  if (!d) return "";
  const date = new Date(d);
  if (Number.isNaN(date.getTime())) return String(d);
  return date.toISOString().slice(0, 10);
};

export const EXPORT_REPORTS = {
  customers: {
    label: "Customers & Vendors",
    filename: "customers",
    sheetName: "Customers",
    columns: [
      { key: "name", header: "Name", default: true, get: (r) => r.name || "" },
      { key: "phone", header: "Phone", default: true, get: (r) => r.phone || "" },
      { key: "email", header: "Email", default: true, get: (r) => r.email || "" },
      { key: "type", header: "Party Type", default: true, get: (r) => r.type || "" },
      { key: "customerType", header: "Category", default: true, get: (r) => r.customerType || "" },
      { key: "gstin", header: "GSTIN", default: true, get: (r) => r.gstin || "" },
      { key: "place", header: "Place", default: false, get: (r) => r.address?.place || "" },
      { key: "state", header: "State", default: false, get: (r) => r.address?.state || "" },
      { key: "stateCode", header: "State Code", default: false, get: (r) => r.address?.stateCode || "" },
    ],
  },
  products: {
    label: "Products",
    filename: "products",
    sheetName: "Products",
    columns: [
      { key: "name", header: "Name", default: true, get: (r) => r.name || "" },
      { key: "code", header: "Code", default: true, get: (r) => r.code || "" },
      { key: "hsnCode", header: "HSN", default: true, get: (r) => r.hsnCode || "" },
      { key: "price", header: "Price", default: true, get: (r) => r.price ?? 0 },
      { key: "taxPercent", header: "Tax %", default: true, get: (r) => r.taxPercent ?? 0 },
      { key: "uom", header: "UOM", default: true, get: (r) => r.uomId?.name || "" },
      { key: "category", header: "Category", default: true, get: (r) => r.categoryId?.name || "" },
    ],
  },
  warehouses: {
    label: "Warehouses",
    filename: "warehouses",
    sheetName: "Warehouses",
    columns: [
      { key: "name", header: "Name", default: true, get: (r) => r.name || "" },
      { key: "code", header: "Code", default: true, get: (r) => r.code || "" },
    ],
  },
  sales: {
    label: "Sales Invoices",
    filename: "sales-invoices",
    sheetName: "Sales",
    columns: [
      { key: "invoiceNo", header: "Invoice No", default: true, get: (r) => r.invoiceNo || "" },
      { key: "invoiceDate", header: "Date", default: true, get: (r) => fmtDate(r.invoiceDate) },
      { key: "customer", header: "Customer", default: true, get: (r) => r.customerSnapshot?.name || "" },
      { key: "salesType", header: "Type", default: true, get: (r) => r.salesType || "" },
      { key: "saleMode", header: "Sale Mode", default: true, get: (r) => r.saleMode || "cash" },
      { key: "grandTotal", header: "Total", default: true, get: (r) => r.grandTotal ?? 0 },
      { key: "balanceAmount", header: "Balance", default: true, get: (r) => r.balanceAmount ?? 0 },
      { key: "paymentStatus", header: "Status", default: true, get: (r) => r.paymentStatus || "" },
    ],
  },
  purchase: {
    label: "Purchase Invoices",
    filename: "purchase-invoices",
    sheetName: "Purchase",
    columns: [
      { key: "invoiceNo", header: "Invoice No", default: true, get: (r) => r.invoiceNo || "" },
      { key: "purchaseDate", header: "Date", default: true, get: (r) => fmtDate(r.purchaseDate) },
      { key: "vendor", header: "Vendor", default: true, get: (r) => r.vendorSnapshot?.name || "" },
      { key: "grandTotal", header: "Total", default: true, get: (r) => r.grandTotal ?? 0 },
      { key: "balanceAmount", header: "Balance", default: true, get: (r) => r.balanceAmount ?? 0 },
      { key: "paymentStatus", header: "Status", default: true, get: (r) => r.paymentStatus || "" },
    ],
  },
  receipts: {
    label: "Receipt Vouchers",
    filename: "receipts",
    sheetName: "Receipts",
    columns: [
      { key: "voucherNo", header: "Voucher No", default: true, get: (r) => r.voucherNo || "" },
      { key: "date", header: "Date", default: true, get: (r) => fmtDate(r.date) },
      { key: "customer", header: "Customer", default: true, get: (r) => r.partySnapshot?.name || "" },
      { key: "paymentMode", header: "Mode", default: true, get: (r) => r.paymentMode || "" },
      { key: "totalAmount", header: "Amount", default: true, get: (r) => r.totalAmount ?? 0 },
    ],
  },
  payments: {
    label: "Vendor Payments",
    filename: "payments",
    sheetName: "Payments",
    columns: [
      { key: "voucherNo", header: "Voucher No", default: true, get: (r) => r.voucherNo || "" },
      { key: "date", header: "Date", default: true, get: (r) => fmtDate(r.date) },
      { key: "vendor", header: "Vendor", default: true, get: (r) => r.partySnapshot?.name || "" },
      { key: "paymentMode", header: "Mode", default: true, get: (r) => r.paymentMode || "" },
      { key: "totalAmount", header: "Amount", default: true, get: (r) => r.totalAmount ?? 0 },
    ],
  },
  expenses: {
    label: "Expenses",
    filename: "expenses",
    sheetName: "Expenses",
    columns: [
      { key: "expenseNo", header: "Expense No", default: true, get: (r) => r.expenseNo || "" },
      { key: "date", header: "Date", default: true, get: (r) => fmtDate(r.date) },
      { key: "category", header: "Category", default: true, get: (r) => r.category || "" },
      { key: "title", header: "Title", default: true, get: (r) => r.title || "" },
      { key: "amount", header: "Amount", default: true, get: (r) => r.amount ?? 0 },
      { key: "paymentMode", header: "Payment Mode", default: true, get: (r) => r.paymentMode || "" },
    ],
  },
  journals: {
    label: "Journal Entries",
    filename: "journal-entries",
    sheetName: "Journals",
    columns: [
      { key: "journalNo", header: "Journal No", default: true, get: (r) => r.journalNo || "" },
      { key: "entryDate", header: "Date", default: true, get: (r) => fmtDate(r.entryDate) },
      { key: "referenceNo", header: "Reference", default: true, get: (r) => r.referenceNo || "" },
      { key: "referenceType", header: "Source", default: true, get: (r) => r.referenceType || "" },
      { key: "narration", header: "Narration", default: true, get: (r) => r.narration || "" },
      { key: "totalDebit", header: "Debit", default: true, get: (r) => r.totalDebit ?? 0 },
      { key: "totalCredit", header: "Credit", default: true, get: (r) => r.totalCredit ?? 0 },
    ],
  },
  "trial-balance": {
    label: "Trial Balance",
    filename: "trial-balance",
    sheetName: "Trial Balance",
    includeSlNo: false,
    columns: [
      { key: "accountCode", header: "Code", default: true, get: (r) => r.accountCode || "" },
      { key: "accountName", header: "Account", default: true, get: (r) => r.accountName || "" },
      { key: "accountType", header: "Type", default: true, get: (r) => r.accountType || "" },
      { key: "debit", header: "Debit", default: true, get: (r) => r.debitBalance ?? 0 },
      { key: "debitBalance", header: "Dr Balance", default: true, get: (r) => r.debitBalance ?? 0 },
      { key: "credit", header: "Credit", default: true, get: (r) => r.creditBalance ?? 0 },
      { key: "creditBalance", header: "Cr Balance", default: true, get: (r) => r.creditBalance ?? 0 },
    ],
  },
  "customer-balances": {
    label: "Customer Balances",
    filename: "customer-balances",
    sheetName: "Customer Balances",
    columns: [
      { key: "name", header: "Customer", default: true, get: (r) => r.name || "" },
      { key: "phone", header: "Phone", default: true, get: (r) => r.phone || "" },
      { key: "balance", header: "Balance (Dr)", default: true, get: (r) => r.balance ?? 0 },
    ],
  },
  "chart-of-accounts": {
    label: "Chart of Accounts",
    filename: "chart-of-accounts",
    sheetName: "Chart of Accounts",
    includeSlNo: false,
    columns: [
      { key: "code", header: "Code", default: true, get: (r) => r.code || "" },
      { key: "name", header: "Account Name", default: true, get: (r) => r.name || "" },
      { key: "accountType", header: "Type", default: true, get: (r) => r.accountType || "" },
      { key: "type", header: "Type", default: true, get: (r) => r.accountType || "" },
      { key: "subLedger", header: "Sub-ledger", default: true, get: (r) => r.subLedger || "" },
    ],
  },
  "profit-loss": {
    label: "Profit & Loss",
    filename: "profit-loss",
    sheetName: "Profit & Loss",
    includeSlNo: false,
    columns: [
      { key: "section", header: "Section", default: true, get: (r) => r.section || "" },
      { key: "accountCode", header: "Code", default: true, get: (r) => r.accountCode || "" },
      { key: "accountName", header: "Account", default: true, get: (r) => r.accountName || "" },
      { key: "amount", header: "Amount", default: true, get: (r) => r.amount ?? 0 },
    ],
  },
  "balance-sheet": {
    label: "Balance Sheet",
    filename: "balance-sheet",
    sheetName: "Balance Sheet",
    includeSlNo: false,
    columns: [
      { key: "section", header: "Section", default: true, get: (r) => r.section || "" },
      { key: "accountCode", header: "Code", default: true, get: (r) => r.accountCode || "" },
      { key: "accountName", header: "Account", default: true, get: (r) => r.accountName || "" },
      { key: "amount", header: "Amount", default: true, get: (r) => r.amount ?? 0 },
    ],
  },
  "sales-report": {
    label: "Sales Report",
    filename: "sales-report",
    sheetName: "Sales Report",
    columns: [
      { key: "invoiceNo", header: "Invoice No", default: true, get: (r) => r.invoiceNo || "" },
      { key: "invoiceDate", header: "Date", default: true, get: (r) => fmtDate(r.invoiceDate) },
      { key: "salesType", header: "Type", default: true, get: (r) => r.salesType || "" },
      { key: "customer", header: "Customer", default: true, get: (r) => r.customerSnapshot?.name || "" },
      { key: "priceLevel", header: "Price Level", default: true, get: (r) => r.priceLevelSnapshot?.name || "" },
      { key: "netAmount", header: "Net Amount", default: true, get: (r) => r.netAmount ?? 0 },
      { key: "tax", header: "Tax", default: true, get: (r) => r.totalTax ?? 0 },
      { key: "totalTax", header: "Tax", default: true, get: (r) => r.totalTax ?? 0 },
      { key: "grandTotal", header: "Grand Total", default: true, get: (r) => r.grandTotal ?? 0 },
      { key: "status", header: "Status", default: true, get: (r) => r.status || "" },
    ],
  },
  "purchase-report": {
    label: "Purchase Report",
    filename: "purchase-report",
    sheetName: "Purchase Report",
    columns: [
      { key: "invoiceNo", header: "Invoice No", default: true, get: (r) => r.invoiceNo || "" },
      { key: "date", header: "Date", default: true, get: (r) => fmtDate(r.purchaseDate) },
      { key: "purchaseDate", header: "Date", default: true, get: (r) => fmtDate(r.purchaseDate) },
      { key: "vendor", header: "Vendor", default: true, get: (r) => r.vendorSnapshot?.name || r.vendorId?.name || "" },
      { key: "warehouse", header: "Warehouse", default: true, get: (r) => r.warehouseId?.name || "" },
      { key: "netAmount", header: "Net Amount", default: true, get: (r) => r.netAmount ?? 0 },
      { key: "sgst", header: "SGST", default: true, get: (r) => r.totalSGST ?? 0 },
      { key: "cgst", header: "CGST", default: true, get: (r) => r.totalCGST ?? 0 },
      { key: "tax", header: "Tax", default: true, get: (r) => r.totalTax ?? 0 },
      { key: "totalTax", header: "Tax", default: true, get: (r) => r.totalTax ?? 0 },
      { key: "grandTotal", header: "Grand Total", default: true, get: (r) => r.grandTotal ?? 0 },
      { key: "status", header: "Status", default: true, get: (r) => r.status || "" },
    ],
  },
  "stock-report": {
    label: "Stock Report",
    filename: "stock-report",
    sheetName: "Stock Report",
    columns: [
      { key: "item", header: "Item", default: true, get: (r) => r.itemId?.name || "" },
      { key: "code", header: "Code", default: true, get: (r) => r.itemId?.code || "" },
      { key: "hsn", header: "HSN", default: true, get: (r) => r.itemId?.hsnCode || "" },
      { key: "category", header: "Category", default: true, get: (r) => r.itemId?.categoryId?.name || "" },
      { key: "uom", header: "UOM", default: true, get: (r) => r.itemId?.uomId?.name || "" },
      { key: "warehouse", header: "Warehouse", default: true, get: (r) => r.warehouseId?.name || "" },
      { key: "qty", header: "Qty", default: true, get: (r) => r.qty ?? 0 },
      { key: "rate", header: "Rate", default: true, get: (r) => r.rate ?? 0 },
      { key: "sgst", header: "SGST", default: true, get: (r) => r.sgst ?? 0 },
      { key: "cgst", header: "CGST", default: true, get: (r) => r.cgst ?? 0 },
      { key: "stockValue", header: "Stock Value", default: true, get: (r) => r.stockValue ?? 0 },
    ],
  },
  "ledger-report": {
    label: "Stock Ledger",
    filename: "stock-ledger",
    sheetName: "Stock Ledger",
    columns: [
      { key: "date", header: "Date", default: true, get: (r) => fmtDate(r.createdAt) },
      { key: "item", header: "Item", default: true, get: (r) => r.itemId?.name || "" },
      { key: "warehouse", header: "Warehouse", default: true, get: (r) => r.warehouseId?.name || "" },
      { key: "movementType", header: "Movement", default: true, get: (r) => r.movementType || "" },
      { key: "qty", header: "Qty", default: true, get: (r) => r.qty ?? 0 },
      { key: "value", header: "Value", default: true, get: (r) => r.value ?? 0 },
      { key: "referenceNo", header: "Reference", default: true, get: (r) => r.referenceNo || "" },
    ],
  },
  "shop-report": {
    label: "Shop Report",
    filename: "shop-report",
    sheetName: "Shop Report",
    columns: [
      { key: "date", header: "Date", default: true, get: (r) => fmtDate(r.date) },
      { key: "party", header: "Party", default: true, get: (r) => r.partyName || "" },
      { key: "type", header: "Type", default: true, get: (r) => r.entryType || "" },
      { key: "referenceNo", header: "Reference", default: true, get: (r) => r.referenceNo || "" },
      { key: "debit", header: "Debit", default: true, get: (r) => r.debit ?? 0 },
      { key: "credit", header: "Credit", default: true, get: (r) => r.credit ?? 0 },
      { key: "balance", header: "Balance", default: true, get: (r) => r.balance ?? 0 },
    ],
  },
  "sales-history": {
    label: "Sales History",
    filename: "sales-history",
    sheetName: "Sales History",
    columns: [
      { key: "invoiceNo", header: "Invoice No", default: true, get: (r) => r.invoiceNo || "" },
      { key: "date", header: "Date", default: true, get: (r) => fmtDate(r.date) },
      { key: "salesType", header: "Type", default: true, get: (r) => r.salesType || "" },
      { key: "customer", header: "Customer", default: true, get: (r) => r.customer || "" },
      { key: "itemName", header: "Item", default: true, get: (r) => r.itemName || "" },
      { key: "qty", header: "Qty", default: true, get: (r) => r.qty ?? 0 },
      { key: "rate", header: "Rate", default: true, get: (r) => r.rate ?? 0 },
      { key: "total", header: "Total", default: true, get: (r) => r.total ?? 0 },
    ],
  },
  "purchase-history": {
    label: "Purchase History",
    filename: "purchase-history",
    sheetName: "Purchase History",
    columns: [
      { key: "invoiceNo", header: "Invoice No", default: true, get: (r) => r.invoiceNo || "" },
      { key: "date", header: "Date", default: true, get: (r) => fmtDate(r.date) },
      { key: "vendor", header: "Vendor", default: true, get: (r) => r.vendor || "" },
      { key: "itemName", header: "Item", default: true, get: (r) => r.itemName || "" },
      { key: "qty", header: "Qty", default: true, get: (r) => r.qty ?? 0 },
      { key: "rate", header: "Rate", default: true, get: (r) => r.rate ?? 0 },
      { key: "total", header: "Total", default: true, get: (r) => r.total ?? 0 },
    ],
  },
  "sales-return-history": {
    label: "Sales Return History",
    filename: "sales-return-history",
    sheetName: "Sales Return History",
    columns: [
      { key: "returnNo", header: "Return No", default: true, get: (r) => r.returnNo || "" },
      { key: "date", header: "Date", default: true, get: (r) => fmtDate(r.date) },
      { key: "customer", header: "Customer", default: true, get: (r) => r.customer || "" },
      { key: "itemName", header: "Item", default: true, get: (r) => r.itemName || "" },
      { key: "qty", header: "Qty", default: true, get: (r) => r.qty ?? 0 },
      { key: "rate", header: "Rate", default: true, get: (r) => r.rate ?? 0 },
      { key: "total", header: "Total", default: true, get: (r) => r.total ?? 0 },
    ],
  },
  "purchase-return-history": {
    label: "Purchase Return History",
    filename: "purchase-return-history",
    sheetName: "Purchase Return History",
    columns: [
      { key: "returnNo", header: "Return No", default: true, get: (r) => r.returnNo || "" },
      { key: "date", header: "Date", default: true, get: (r) => fmtDate(r.date) },
      { key: "vendor", header: "Vendor", default: true, get: (r) => r.vendor || "" },
      { key: "itemName", header: "Item", default: true, get: (r) => r.itemName || "" },
      { key: "qty", header: "Qty", default: true, get: (r) => r.qty ?? 0 },
      { key: "rate", header: "Rate", default: true, get: (r) => r.rate ?? 0 },
      { key: "total", header: "Total", default: true, get: (r) => r.total ?? 0 },
    ],
  },
  "expense-report": {
    label: "Expense Report",
    filename: "expense-report",
    sheetName: "Expense Report",
    columns: [
      { key: "expenseNo", header: "Expense No", default: true, get: (r) => r.expenseNo || "" },
      { key: "date", header: "Date", default: true, get: (r) => fmtDate(r.date) },
      { key: "category", header: "Category", default: true, get: (r) => r.category || "" },
      { key: "title", header: "Title", default: true, get: (r) => r.title || "" },
      { key: "amount", header: "Amount", default: true, get: (r) => r.amount ?? 0 },
      { key: "paymentMode", header: "Payment Mode", default: true, get: (r) => r.paymentMode || "" },
    ],
  },
};

export const getReportConfig = (reportType) => EXPORT_REPORTS[reportType] || null;

export const listColumnMeta = (reportType) => {
  const config = getReportConfig(reportType);
  if (!config) return null;
  return listColumnMetaWithSlNo(config, { includeSlNo: config.includeSlNo !== false });
};
